language: python
python:
    - '3.4'
    - '3.3'
    - '2.7'
    - '2.6'

before_install:
    - sudo apt-get install tidy
install:
    - python setup.py install
script:
    - python test/test_hoep.py
